version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    container_name: api
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./src/data:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: skills_evaluation

volumes:
  mongo-data:
