version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: api
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    container_name: streamlit
    volumes:
      - ./src:/app/src
    command: ["conda", "run", "-n", "streamlit-env", "streamlit", "run", "/app/src/front/rules_creation.py"]

  streamlit-user-interface:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    container_name: streamlit-user-interface
    volumes:
      - ./src:/app/src
    command: ["conda", "run", "-n", "streamlit-env", "streamlit", "run", "/app/src/front/user_interface.py"]

  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./src/data:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: skills_evaluation

volumes:
  mongo-data:
