name: skillsevaluation
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
      - https://github.com/explosion/spacy-models/releases/download/es_core_news_lg-3.4.0/es_core_news_lg-3.4.0-py3-none-any.whl
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.4.1/en_core_web_lg-3.4.1-py3-none-any.whl
      - cmake==3.22.6
      - deepface==0.0.75
      - fastapi==0.85.0
      - ffmpeg-python==0.2.0
      - gensim==4.2.0
      - keras==2.10.0
      - matplotlib==3.6.0
      - moviepy==2.0.0.dev2
      - networkx==3.1
      - nltk==3.7
      - numpy==1.23.4
      - opencv-python-headless==4.6.0.66
      - praat-parselmouth==0.4.2
      - psutil
      - pyphen==0.13.0
      - scikit-fuzzy==0.4.2
      - scikit-learn==1.1.3
      - spacy==3.4.1
      - TextGrid==1.5
      - uvicorn==0.18.3
      - git+https://github.com/openai/whisper.git
      - openai==1.35.3
      - reportlab==4.2.5
      - streamlit==1.14.0
      - tensorflow==2.10.1
      - protobuf==3.19.6
      - pymongo==4.10.1
      - python-decouple==3.8
      - httpx==0.27.0
      - scipy==1.10.1
      - pandas==1.4.3
